Pass icon components, not strings, to Disclosure
Sundsvallskommun/web-app-draken-public pull request #4
Opened 2024-10-28 08:06 UTC by hensankom

Disclosure-komponenten vill ha ikon-komponenter för att rätt visa dem.

## Types of changes

- [X] Bug fix
- [ ] New feature
- [ ] Removed feature
- [ ] Code style update (formatting etc.)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes

## Does this PR introduce a breaking change?
- [ ] Yes (I have stepped the version number accordingly)
- [ ] No
      
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have added/updated tests to cover my changes (if applicable).

2024-10-28 08:07 UTC, hensankom commented
jira https://jira.sundsvall.se/browse/DRAKEN-568

2024-10-30 09:01 UTC, danneSvall requested changes

2024-10-30 12:43 UTC, hensankom commented on frontend/src/casedata/components/errand/tabs/contract/lagenhetsarrende.tsx
> +        icon={<Icon name="clipboard-list" />}
bra spanat!

2024-11-04 12:03 UTC, danneSvall approved these changes

2024-11-04 12:28 UTC, merged